name       : python-requests-mock
version    : 1.7.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/1c/62/e64412925abe4531a48502ae2c6269f18bf83acb86503337fe1ae74d1e7d/requests-mock-1.7.0.tar.gz : 88d3402dd8b3c69a9e4f9d3a73ad11b15920c6efd36bc27bf1f701cf4a8e4646
license    : Apache-2.0
component  : programming.python
summary    : requests-mock provides a building block to stub out the HTTP requests
    portions of your testing code
description: |
    The requests-mock library at its core is simply a transport adapter that can be preloaded with responses that are returned if certain URIs are requested. This is particularly useful in unit tests where you want to return known responses from HTTP requests without making actual calls.
builddeps  :
    - pbr
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install

