name       : python-requests-mock
version    : 1.4.0
release    : 1
source     :
    - https://pypi.python.org/packages/68/a1/1d507403f75f633e86cacceb93a03ae1dc777cdf5d9aa9d6009b2e2a0e7f/requests-mock-1.4.0.tar.gz : 2931887853c42e1d73879983d5bf03041109472991c5b4b8dba5d11ed23b9d0b
license    : Apache-2.0
component  : programming.python
summary    : requests-mock provides a building block to stub out the HTTP requests portions of your testing code
description: |
    The requests-mock library at its core is simply a transport adapter that can be preloaded with responses that are returned if certain URIs are requested. This is particularly useful in unit tests where you want to return known responses from HTTP requests without making actual calls.
builddeps  :
    - pbr
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install

