name       : python-requests-mock
version    : 1.9.3
release    : 7
source     :
    - https://pypi.io/packages/source/r/requests-mock/requests-mock-1.9.3.tar.gz : 8d72abe54546c1fc9696fa1516672f1031d72a55a1d66c85184f972a24ba0eba
license    : Apache-2.0
component  : programming.python
summary    : requests-mock provides a building block to stub out the HTTP requests portions of your testing code
description: |
    The requests-mock library at its core is simply a transport adapter that can be preloaded with responses that are returned if certain URIs are requested. This is particularly useful in unit tests where you want to return known responses from HTTP requests without making actual calls.
builddeps  :
    - pbr
build      : |
    %python3_setup
install    : |
    %python3_install
